### PR TITLE
Chore/setup repo

### PR DESCRIPTION
**Pull request by LuisRickert**
With this PR we setup the basic structure for the KIT Documentation as recommended by the Tractus-x Devhub as stated [here](https://eclipse-tractusx.github.io/docs/kit-process/processes/update-documentation#schema) additionally we introduce a markdown linter to ensure a proper format of these files

### CODE REVIEW

**Review by SebastianBezold — CHANGES_REQUESTED** [review]
Hi @LuisRickert, this repo is not yet initialized at all. Also this PR does not contain any of the needed legal documentation, so it must not be merged. 
See [TRG 7.00](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-00) for an overview of necessary files and annotations.

In addition, the docs you linked (and wrote), do explain a completely different approach. The Docs are talking about a fork and dedicated directory for a KIT. In my opinion this would also make much more sense. Advantages would be:
- No need to copy/paste the linting workflows
- No risk of being out of date with linting rules of the website repo itself
- No separate legal docs for repo setup needed besides the CC-BY-4.0 annotation and in-text references to Apache-2.0

Will there be other content than the five files you included in this PR? If not, I would rather move this to the website repo itself and delete this repo here. If we will decide on more content in the future, we could always move it out later on of course

/cc @AngelikaWittek

**Comment by SebastianBezold** [comment]
Hi @LuisRickert,

yes exactly! Every repository does need these files. We had the discussion on adding the files at repo creation, but the consent always was, that it is necessary for the repository maintainers to understand the reason behind why these files are necessary. 

If there will be more content in this repository, I think it is fine to have it as repo, but that comes with maintaining the legal docs + `DEPENDENCIES` and so on

**Comment by AngelikaWittek** [comment]
Hi @LuisRickert,

please be aware that the NOTICE file is not a static template, insert your infos there.
Furthermore please care about third party (e.g. fonts, images, icons) content and make the attributions there.
Please see TRG 7 or the [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/).

/cc @SebastianBezold

**Comment by LuisRickert** [comment]
closed since @ChristopherWinterZF has this done [here](https://github.com/eclipse-tractusx/pcf-exchange-kit/pull/2)

**Pull request closed without merging**
